services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - lifetimeline_node_modules:/app/node_modules
    command: sh -c "pnpm run dev"
    networks:
      lifetimeline_default:
  cypress:
    image: ghcr.io/naruhiyo/life-timeline-cypress
    volumes:
      - .:/app
      - lifetimeline_node_modules:/app/node_modules
    environment:
      HOST_FQDN: web
    networks:
      lifetimeline_default:
volumes:
  lifetimeline_node_modules:
networks:
  lifetimeline_default:
