services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - lifetimeline_node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
      - lifetimeline_default
volumes:
  lifetimeline_node_modules:
networks:
  lifetimeline_default:
    external: true
