services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - lifetimeline_node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      lifetimeline_default:
  cypress:
    build:
      context: .
      dockerfile: cypress.Dockerfile
    volumes:
      - .:/app
    environment:
      HOST_FQDN: web
    networks:
      lifetimeline_default:
volumes:
  lifetimeline_node_modules:
networks:
  lifetimeline_default:
