'use client'
import '@/components/globals.css'
import { Navbar, NavbarBrand, Image, Spacer } from '@nextui-org/react'
import type { Metadata } from 'next'
import { useEffect } from 'react'
import { DBLogic } from '@/api/DBLogic'
import { Providers } from '@/providers'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    { rel: 'icon', url: '/images/favicon.ico' },
    { rel: 'apple-touch-icon', url: '/images/apple-touch-icon.png' },
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const closeIndexedDB = async (): Promise<void> => {
    const logic = new DBLogic()
    await logic.close()
  }

  useEffect(() => {
    window.addEventListener('beforeunload', (e: BeforeUnloadEvent) => {
      closeIndexedDB()
    })
  }, [])

  return (
    <html lang='en' className='dark'>
      <body>
        <Navbar shouldHideOnScroll isBordered position='static'>
          <NavbarBrand>
            <Image height={36} width={36} isBlurred src='/images/logo.png' alt='Logo' />
            <Spacer x={4} />
            <p className='font-bold '>Lie-tfimeline</p>
          </NavbarBrand>
        </Navbar>
        <Providers>
          <main className='main'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
