'use client'
import '@/components/globals.css'
import type { Metadata } from 'next'
import { useEffect } from 'react'
import { Providers } from './providers'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const closeIndexedDB = async (): Promise<void> => {
    const dymanicLogic = await import('@/api/DBLogic')
    const logic = new dymanicLogic.DBLogic()
    await logic.close()
  }

  useEffect(() => {
    window.addEventListener('beforeunload', (e: BeforeUnloadEvent) => {
      closeIndexedDB()
    })
  }, [])

  return (
    <html lang='en' className='dark'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
