name: dockership

on:
  push:
    branches:
      - sandbox/LT-57_add_dockership_no_modify_dockerfile
    paths:
      - 'cypress.Dockerfile'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/cypress
          tags: |
            type=raw,value=latest
      - name: Build and Push a Docker Image
        uses: docker/build-push-action@v5
        with:
          file: cypress.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

