name: reviewdog
on: [pull_request]
jobs:
  npm-run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      # Reviewdog is currently not supported ESLint format, so change the output format to rdjson by using index.js
      # In package.json, we use index.js to change linter output format.
      # Therefore, following reviewdog command specify rdjson in -f option.
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: (npm run lint 2>&1 | grep -o '{.*}' || echo "{}") | reviewdog -f=rdjson -reporter=github-pr-review -diff="git diff FETCH_HEAD" -fail-on-error=true
      - name: Run prettier to check format
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ACTION_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          npm run format:check \
          || gh pr comment ${{ github.event.pull_request.number }} --body "Run [#${GITHUB_RUN_ID}]($ACTION_URL): Format is invalid! Please run \`npm run format\`."
