name: test
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:cypress-13.0.0-node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.5
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit test
        run: pnpm run test
      - name: Run E2E test
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
          browser: chrome
      # Ref: https://github.com/cypress-io/github-action#artifacts
      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
