name: test
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run unit test
        run: npm run test
      - name: Run E2E test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      # Ref: https://github.com/cypress-io/github-action#artifacts
      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
