name: test
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      # ISSUE: If use below command, you have to start local server on Github Actions.
      # TODO: Enable below command
      # - name: Run E2E test
      #   run: npm run cypress:ci
